### PR TITLE
[installer]: Prevent filesystem corruption

### LINKED ISSUE #6267: [installer.sh] Filesystem corruption observed when sonic_version.yml is modified
**Description**

SONiC installer corrupts filesystem in case `/etc/sonic/sonic_version.yml` contains invalid image version:
https://github.com/Azure/sonic-buildimage/blob/master/installer/x86_64/install.sh#L448
```
elif [ "$install_env" = "sonic" ]; then
    demo_mnt="/host"
    eval running_sonic_revision=$(cat /etc/sonic/sonic_version.yml | grep build_version | cut -f2 -d" ")
    # Prevent installing existing SONiC if it is running
    if [ "$image_dir" = "image-$running_sonic_revision" ]; then
        echo "Not installing SONiC version $running_sonic_revision, as current running SONiC has the same version"
        exit 0
    fi
    # Remove extra SONiC images if any
    for f in $demo_mnt/image-* ; do
        if [ -d $f ] && [ "$f" != "$demo_mnt/image-$running_sonic_revision" ] && [ "$f" != "$demo_mnt/$image_dir" ]; then
            echo "Removing old SONiC installation $f"
            rm -rf $f
        fi
    done
else
```

**Steps to reproduce the issue:**
1. Edit `/etc/sonic/sonic_version.yml` with invalid image version
2. sonic-installer install sonic-mellanox.bin

**Describe the results you received:**
```
root@sonic:/home/admin# sonic-installer install sonic-mellanox.bin
New image will be installed, continue? [y/N]: y
Installing image SONiC-OS-201911.255-fd05c258 and setting it as default...
Command: bash ./sonic-mellanox.bin
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/1a946ebbee4a4af44d314826c485fd542f841c3e0f4fec53a7296b2b49722e62/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/929df70858946fcbb8830e9bae0d39e612b16507312cc521e1fe5b4df7704423/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/d2fde6fb91ee1a62f931c8739910d020d54d793f87a6f237c2dc84fdbeab6759/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/6d87ec038d86e29c3a3ce1a8be12e83c1b7c330fee0b231f4db7eea409d4c5f1/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/bee93c75bf8ea6dce484d1cb0a11f58724d4c00d0ccfda0496a88eb1f0da0059/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/8ae3456a72f4715eeb7ce5ba232dba7040371a52803d85b7d55e6287792ea8bb/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/9662df105b9317f37265c52e04dc9fe44384b76ab7b320e13e29a539cd1f1349/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/3c101281ca77bb68bc50a73fa557b4d63d4039b6de300e944baf9936a108a059/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/containers/b678d4630697ddd149487e9ff54e194e0fd5e3d3ff7b9c6dfa3aed1f408b9e2f/mounts/shm': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/ba48b90bd70442c7c6bec371c988503005b6e222e72815e28702380e272b507d/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/08d9da59440808cb503ef89d4fb4d1f25ce015e611d4f4c5eaff69a2b2b6e9a6/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/29fcc0df8b8c379f679558fab436fa939a5d0bd7bfa5a548baea395e460b45d6/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/b14944238e764cbd7b6bbdab484cb1a3909ac6590ba83e850ceb696624af6736/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/85ed0ce70451b7d62aca25853c9ce8e0f420cec0c563262b51d0d9a413adab31/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/e076562a4da9e423a5dccc01b4a2391dce3d25bbd894c5b8bc4fba56c226d188/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/fb5a6d60889f2b9c5726d2974972e91cb074f3a747da63fbec7e2bec0448c92c/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/5fd00b26d022a607616e7bd8e553e45f943bd28234097852c4073f87ec0a2f48/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/1960d8f636dc1a5fe4aa1c1f79adad6944c43dd064b5334c9126d5507007b866/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/7b5fe33c917bc51e0b2afc023f1506c61c2c8be4605a537186124dd46ed52924/merged': Device or resource busy
rm: cannot remove '/host/image-master.497-ee8c3d34/docker/overlay2/e12ec8ce63861e5922f20d3a19726ccfeb1db5dbe29af0d1e99279cd93ada620/merged': Device or resource busy
Verifying image checksum ... OK.
Preparing image archive ... OK.
Installing SONiC in SONiC
ONIE Installer: platform: x86_64-mellanox-r0
onie_platform: x86_64-mlnx_msn2700-r0
Removing old SONiC installation /host/image-master.497-ee8c3d34

root@sonic:/home/admin# sudo reboot
Traceback (most recent call last):
  File "/usr/local/bin/sonic-installer", line 5, in <module>
    from sonic_installer.main import sonic_installer
  File "/usr/local/lib/python3.7/dist-packages/sonic_installer/main.py", line 11, in <module>
    from swsscommon.swsscommon import SonicV2Connector
ModuleNotFoundError: No module named 'swsscommon'
/var/log: 3.9 GiB (4138811392 bytes) trimmed on /dev/loop1
hwclock: cannot open /etc/adjtime: No such file or directory
Mon 21 Dec 2020 07:02:49 PM UTC Rebooting with platform x86_64-mlnx_msn2700-r0 specific tool ...
Traceback (most recent call last):
  File "/usr/local/bin/sonic-installer", line 5, in <module>
    from sonic_installer.main import sonic_installer
  File "/usr/local/lib/python3.7/dist-packages/sonic_installer/main.py", line 11, in <module>
    from swsscommon.swsscommon import SonicV2Connector
ModuleNotFoundError: No module named 'swsscommon'
Traceback (most recent call last):
  File "/usr/local/bin/sonic-installer", line 5, in <module>
    from sonic_installer.main import sonic_installer
  File "/usr/local/lib/python3.7/dist-packages/sonic_installer/main.py", line 11, in <module>
    from swsscommon.swsscommon import SonicV2Connector
ModuleNotFoundError: No module named 'swsscommon'

INFO: firmware is up to date

/usr/share/sonic/device/x86_64-mlnx_msn2700-r0/platform_reboot: line 24: 1: No such file or directory
```

After reboot:
```
 +----------------------------------------------------------------------------+
 |*SONiC-OS-master.497-ee8c3d34                                               |
 | ONIE                                                                       |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 +----------------------------------------------------------------------------+

      Use the ^ and v keys to select which entry is highlighted.
      Press enter to boot the selected OS, `e' to edit the commands
      before booting or `c' for a command-line.
Loading SONiC-OS OS kernel ...
error: you need to load the kernel first.oot/vmlinuz-4.19.0-9-2-amd64' not
found.
Press any key to continue...ramdisk ...
```

**Describe the results you expected:**
SONiC image firmware upgrade should be reliable: `sonic_version.yml` is not trusted

**Additional information you deem important (e.g. issue happens only occasionally):**
**Output of `show version`:**
```
(paste your output here)
```

**Attach debug file `sudo generate_dump`:**
```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by nazariig**
Signed-off-by: Nazarii Hnydyn <nazariig@nvidia.com>

This improvement reads current SONiC version directly from `/proc/cmdline`.
it supports `grub/aboot/uboot` bootloaders.

**Code snippet**:
```bash
cat /proc/cmdline | sed -n 's/^.*loop=\/*image-\(\S\+\)\/.*$/\1/p'
```

**Description**:
```
-n         don't print lines
s          substitute
^.*        matches anything before the <image_version>
loop=      matches <loop> kernel parameter
\/*image-  matches <image_version> prefix
\(\S\+\)   matches <image_version> group and assigns it to \1
\/.*$      matches anything after the <image_version>
\1         replace everything with <image_version>
p          print it
```

closes #6267

#### Why I did it
* To fix #6267

#### How I did it
* Fixed installer scripts

#### How to verify it
1. Write invalid SONiC version to sonic_version.yml
2. Run SONiC-To-SONiC update

#### Which release branch to backport (provide reason below if selected)

- [ ] 201811
- [x] 201911
- [x] 202006
- [X] 202012

#### Description for the changelog

* N/A

#### A picture of a cute animal (not mandatory but encouraged)
```
      .---.        .-----------
     /     \  __  /    ------
    / /     \(  )/    -----
   //////   ' \/ `   ---
  //// / // :    : ---
 // /   /  /`    '--
//          //..\\
       ====UU====UU====
           '//||\\`
             ''``
```

### CODE REVIEW

**Review by jleveque — APPROVED** [review]

File: installer/arm64/install.sh [hunk 1]
```diff
@@ -99,6 +99,12 @@ if [ "$install_env" = "onie" ]; then
 elif [ "$install_env" = "sonic" ]; then
     demo_mnt="/host"
     eval running_sonic_revision=$(cat /etc/sonic/sonic_version.yml | grep build_version | cut -f2 -d" ")
```
Comment (nazariig) [inline installer/arm64/install.sh:101]: Still, relying on /etc/sonic/sonic version.yml is not robust enough. Probably, we need to improve a logic which retrieves the current running image. Maybe /proc/cmdline will be good enough...

Comment (qiluo-msft) [reply installer/arm64/install.sh:101]: `/proc/cmdline` should be much better solution. Even you checked the image exists on disk, it may not the running version.

---
In reply to: [610042919](https://github.com/Azure/sonic-buildimage/pull/7264#discussion_r610042919) [](ancestors = 610042919)

**Review by qiluo-msft — CHANGES_REQUESTED** [review]
Blocked

File: installer/arm64/install.sh (hunk 1 above)
Comment (nazariig) [reply installer/arm64/install.sh]: @qiluo-msft fixed

**Comment by nazariig** [comment]
@antony-rheneus FYI

**Review by antony-rheneus — APPROVED** [review]

**Review by jleveque — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@qiluo-msft could  you please review following the review comments handling?

**Review by qiluo-msft — APPROVED** [review]
